"""Read-only DuckDB session and query helpers for the web server.

Opens an in-memory consumer DB that ATTACHes the producer's DuckDB file
read-only (see `source_db.py`). The producer file is the single source
of truth; the consumer never materializes anything.
"""
from __future__ import annotations

import threading
from datetime import datetime, timezone
from typing import Any

import duckdb
import pandas as pd

from repricing_forensics.config import default_paths, default_schedule_name
from repricing_forensics.labels import ADDRESS_PROJECT_LABELS
from repricing_forensics.source_db import open_session, resolve_producer_db_path

SCHEDULE_NAME = default_schedule_name()

_paths = default_paths()
_conn: duckdb.DuckDBPyConnection | None = None
_conn_producer_mtime: float | None = None
_labels: dict[str, str] = {}
_db_lock = threading.Lock()


def get_conn() -> duckdb.DuckDBPyConnection:
    """Return a shared read-only consumer session, reopening if the
    producer file has been replaced since last access."""
    global _conn, _conn_producer_mtime
    producer_path = resolve_producer_db_path()
    try:
        mtime = producer_path.stat().st_mtime
    except FileNotFoundError:
        mtime = None
    if _conn is not None and mtime != _conn_producer_mtime:
        try:
            _conn.close()
        except Exception:
            pass
        _conn = None
    if _conn is None:
        _conn = open_session(producer_path, SCHEDULE_NAME)
        _conn_producer_mtime = mtime
    return _conn


def close_conn() -> None:
    global _conn, _conn_producer_mtime
    if _conn is not None:
        _conn.close()
        _conn = None
        _conn_producer_mtime = None


def query(sql: str) -> list[dict[str, Any]]:
    """Execute SQL and return a list of dicts."""
    with _db_lock:
        df = get_conn().execute(sql).df()
    # `df.where(df.notna(), None)` does not coerce NaN to None on float columns
    # (pandas preserves the float dtype, so None round-trips back to NaN). Cast
    # to object first so None survives `to_dict`.
    return df.astype(object).where(df.notna(), None).to_dict(orient="records")


def query_df(sql: str) -> pd.DataFrame:
    """Execute SQL and return a DataFrame."""
    with _db_lock:
        return get_conn().execute(sql).df()


def query_scalar(sql: str, default: Any = None) -> Any:
    """Execute SQL and return the single scalar result, or default if empty."""
    with _db_lock:
        row = get_conn().execute(sql).fetchone()
    if row is None:
        return default
    return row[0]


def load_labels() -> dict[str, str]:
    """Load contract labels from the hardcoded map + the optional
    `cache/contract_labels.csv` enrichment.

    The CSV used to be generated by `scripts/build_contract_labels.py`
    (sourcify + etherscan lookups), which was removed in the storage
    redesign cleanup — there's no in-repo generator anymore. Existing
    cached CSVs from a prior run are still honored. Once the producer
    ships `contract_metadata`, the dashboard can prefer those labels and
    this path becomes optional.
    """
    global _labels
    if _labels:
        return _labels
    _labels = dict(ADDRESS_PROJECT_LABELS)
    labels_csv = _paths.cache_dir / "contract_labels.csv"
    if labels_csv.exists():
        df = pd.read_csv(labels_csv)
        for _, row in df.iterrows():
            _labels[str(row["address"]).lower()] = row["name"]
    return _labels


def label_address(addr: str | None) -> str:
    """Return project label for an address, or the address itself."""
    if not isinstance(addr, str) or not addr:
        return "unknown"
    labels = load_labels()
    return labels.get(addr.lower(), addr)


def db_mtime() -> datetime:
    """Return the last-modified time of the producer DuckDB file."""
    p = resolve_producer_db_path()
    if p.exists():
        return datetime.fromtimestamp(p.stat().st_mtime, tz=timezone.utc)
    return datetime.now(tz=timezone.utc)
